/**
 * Aditya-L1 Design System Tokens
 * Source of truth for styling constants, matching Tailwind configurations.
 */

export const TOKENS = {
  colors: {
    surface: '#f7f9fc',
    surfaceDim: '#d8dadd',
    surfaceBright: '#f7f9fc',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f2f4f7',
    surfaceContainer: '#eceef1',
    surfaceContainerHigh: '#e6e8eb',
    surfaceContainerHighest: '#e0e3e6',
    onSurface: '#191c1e',
    onSurfaceVariant: '#464555',
    inverseSurface: '#2d3133',
    inverseOnSurface: '#eff1f4',
    outline: '#767586',
    outlineVariant: '#c7c4d7',
    surfaceTint: '#4949d9',
    primary: '#4140d1',
    onPrimary: '#ffffff',
    primaryContainer: '#5b5ceb',
    onPrimaryContainer: '#f5f2ff',
    inversePrimary: '#c1c1ff',
    secondary: '#ae3104',
    onSecondary: '#ffffff',
    secondaryContainer: '#fe693c',
    onSecondaryContainer: '#601600',
    tertiary: '#55575d',
    onTertiary: '#ffffff',
    tertiaryContainer: '#6e6f75',
    onTertiaryContainer: '#f3f3fa',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    success: '#22c55e',
    warning: '#f59e0b',
    critical: '#ef4444',
    sidebarDark: '#111318',
    sidebarFooter: '#0e1014',
    cardBorder: '#e8ecf2',
    terminalBg: '#0d1117',
  },
  borderRadius: {
    xs: '4px',
    sm: '6px',
    md: '8px',
    lg: '12px',
    xl: '18px', // Card radius
    full: '9999px',
  },
  spacing: {
    none: '0px',
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
    xxxl: '64px',
    componentPaddingY: '12px',
    componentPaddingX: '16px',
    containerMargin: '32px',
    sectionGap: '48px',
    gutter: '24px',
  },
  fontFamily: {
    body: 'Inter, sans-serif',
    display: 'Space Grotesk, sans-serif',
    mono: 'JetBrains Mono, monospace',
  },
  fontSize: {
    bodySm: '14px',
    bodyLg: '16px',
    displayLg: '48px',
    headlineMd: '24px',
    labelCaps: '12px',
    numericTelemetry: '18px',
    dataMono: '13px',
  },
  boxShadow: {
    card: '0 10px 30px rgba(15, 23, 42, 0.04)',
    overlay: '0 15px 40px rgba(0, 0, 0, 0.12)',
  },
  transition: {
    default: 'all 0.15s ease-in-out',
    fast: 'all 0.1s ease-in-out',
    slow: 'all 0.3s ease-in-out',
  },
  zIndex: {
    base: '0',
    dropdown: '100',
    sticky: '200',
    fixed: '300',
    modal: '1000',
    popover: '1100',
    toast: '1200',
  },
} as const;

export type TokensType = typeof TOKENS;
