"""
Report Agent — Assembles multi-section Markdown reports from other agents' data.
"""

import logging
from datetime import datetime, timezone
from typing import Any, List
from backend.reasoning.agents.base_agent import BaseAgent, AgentResult, Source

logger = logging.getLogger("SRE.ReportAgent")


class ReportAgent(BaseAgent):
    name = "report"

    def __init__(self, app_state):
        self.app_state = app_state

    async def execute(self, subtask: Any, context: Any) -> AgentResult:
        return self._generate(context, subtask.params.get("query", ""))

    def _generate(self, context: Any, query: str) -> AgentResult:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        predictions = context.predictions or {}
        physics = context.physics or {}
        risk = context.risk_indices or {}
        decision = context.decision_state or {}

        prob = predictions.get("probability", 0.0)
        cls = predictions.get("predicted_class", "Quiet")
        temp = physics.get("temperature_MK", 0.0)
        em = physics.get("emission_measure_log", 0.0)
        op_state = decision.get("operational_state", "NOMINAL")
        mission_risk = risk.get("mission_risk_index", 0.0)

        report = f"""# Aditya-L1 Mission Report
**Generated**: {now}
**Classification**: OPERATIONAL

---

## 1. Executive Summary

The Aditya-L1 Space Weather Intelligence Platform is currently operating in **{op_state}** state. The mission risk index stands at **{mission_risk:.3f}**. The AI ensemble predicts **{cls}-Class** activity at **{prob*100:.1f}%** probability.

## 2. Solar Physics Summary

| Parameter | Value |
|---|---|
| Peak Temperature | {temp:.1f} MK |
| Emission Measure (log) | {em:.2f} |
| Operational State | {op_state} |

{'> ⚠️ Elevated thermal conditions detected.' if temp > 10 else '> Thermal conditions are nominal.'}

## 3. Prediction Summary

| Metric | Value |
|---|---|
| Predicted Class | {cls} |
| Probability | {prob*100:.1f}% |
| Confidence | {predictions.get('confidence', 0)*100:.1f}% |
| Ensemble Agreement | {'Strong' if predictions.get('confidence', 0) > 0.85 else 'Moderate'} |

## 4. Risk Assessment

| Risk Index | Value |
|---|---|
| Mission Risk | {mission_risk:.3f} |
| Radiation Context | {risk.get('radiation_context_index', 0):.3f} |
| HF Blackout | {risk.get('hf_blackout_risk_index', 0):.3f} |

## 5. Digital Twin State

- Active Regions Tracked: {len(context.active_regions) if isinstance(context.active_regions, dict) else 0}
- Selected Region: {context.selected_region_id or 'None'}

## 6. Recommendations

{'1. Increase telemetry sampling rate' if mission_risk > 0.7 else '1. Continue nominal operations'}
{'2. Alert ground station operators' if mission_risk > 0.7 else '2. Standard monitoring cadence'}
{'3. Review ensemble predictions' if prob > 0.5 else '3. No action required'}

---

*Report generated by the Aditya-L1 Scientific Reasoning Engine v1.0*
"""

        return self._make_result(
            content=report,
            confidence=0.95,
            sources=[
                Source(title="Mission Report Generator", module="reasoning", id="report"),
                Source(title="Physics Engine", module="physics_engine", id="summary"),
                Source(title="AI Ensemble", module="ai_engine", id="predictions"),
                Source(title="Mission Intelligence", module="mission_intelligence", id="risk"),
            ],
        )
