//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: chspec
// Function header: chspecFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <XSFunctions/Utilities/funcType.h>

class    XSCallBase;

void  createchspecFunctionMap();

extern "C"  {


	XSCCall      chisoth;
	XSCCall      chgausdem;
}


#endif
