//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: chspec Created :
// Initializer: chspec.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "chspecFunctionMap.h"
#include  <XSFunctions/Utilities/XSCall.h>
#include  <XSFunctions/Utilities/XSModelFunction.h>

extern "C" int Chspec_Init(Tcl_Interp* tclInterp);
extern "C" int Chspec_SafeInit(Tcl_Interp* tclInterp);

int Chspec_Init(Tcl_Interp* tclInterp)
{
        return Chspec_SafeInit(tclInterp);
}

int Chspec_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "chspec";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        XSModelFunction::updateComponentList
              ("/Users/aditya1981/.gemini/antigravity-ide/brain/ead5211d-dfba-45f4-a3a2-adaf18c4ec59/chspec_build/lmodel_chspec.dat");
        createchspecFunctionMap();
        return TCL_OK;

}

