//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: chspec
// Function body: chspecFunctionMap.cxx

#include    "chspecFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>
#include    <XSFunctions/Utilities/XSCall.h>

void 
createchspecFunctionMap()
{


	XSModelFunction::addFunctionPointer( "chisoth",    new XSCall<XSCCall>(chisoth) );
	XSModelFunction::addFunctionPointer( "chgausdem",  new XSCall<XSCCall>(chgausdem) );

}
